#!/usr/bin/env python3
"""Provision a himmy compose deployment: generate ``.env`` + random secrets.

A first-run operator needs a populated ``deploy/compose/.env`` and the secret
files the compose stack reads (``secrets/postgres_password``, and — when
encryption-at-rest is enabled — ``secrets/HIMMY_ENCRYPTION_KEY``). Hand-editing the
template invites two classic mistakes: a weak/blank password, and the
``POSTGRES_PASSWORD`` in ``.env`` diverging from the value in the secret file (the
stack then can't authenticate). This script generates strong random values once and
writes BOTH places consistently.

It is conservative: it refuses to overwrite an existing ``.env`` or secret file
unless ``--force`` (so re-running never silently rotates a live password), and it
does not require the compose file to exist — it creates the ``secrets/`` directory
itself.

Usage:
    python scripts/ops_provision.py                 # write deploy/compose/.env + secrets
    python scripts/ops_provision.py --dir ./mydir   # provision elsewhere
    python scripts/ops_provision.py --force         # rotate/overwrite existing files
    python scripts/ops_provision.py --up            # also `docker compose up -d`
"""

from __future__ import annotations

import argparse
import base64
import secrets
import subprocess
import sys
from pathlib import Path
from typing import Any

_DEFAULT_DIR = "deploy/compose"
_ENV_NAME = ".env"
_SECRETS_SUBDIR = "secrets"
_PG_PASSWORD_FILE = "postgres_password"  # noqa: S105 - a filename, not a credential
_ENCRYPTION_KEY_FILE = "HIMMY_ENCRYPTION_KEY"
_COMPOSE_FILE = "docker-compose.yml"


def _eprint(*args: Any) -> None:
    print(*args, file=sys.stderr)


def _gen_password() -> str:
    return secrets.token_urlsafe(24)


def _gen_api_key() -> str:
    return secrets.token_urlsafe(32)


def _gen_encryption_key() -> str:
    # Base64 of 32 random bytes — the KEK shape the encryption extra expects.
    return base64.b64encode(secrets.token_bytes(32)).decode("ascii")


def _himmy_version() -> str:
    """Resolve the single-sourced version, falling back to the compose default."""
    try:
        from himmy import __version__

        return __version__
    except Exception:  # pragma: no cover - provisioning never needs to fail on this
        return "0.2.0"


def _render_env(pg_password: str, api_key: str) -> str:
    return (
        "# Generated by scripts/ops_provision.py — do not commit. Mirrors the keys\n"
        "# documented in deploy/compose/.env.example.\n"
        "\n"
        "# Image tag applied to the locally built Studio image.\n"
        f"HIMMY_VERSION={_himmy_version()}\n"
        "\n"
        "# Postgres password. MUST match secrets/postgres_password (this script keeps\n"
        "# them in sync). Changing it later also requires resetting the pg volume.\n"
        f"POSTGRES_PASSWORD={pg_password}\n"
        "\n"
        "# Auth hardening — apikey mode requires the internal API key header below.\n"
        "HIMMY_AUTH_MODE=apikey\n"
        f"HIMMY_INTERNAL_API_KEY={api_key}\n"
        "\n"
        "# Hosts allowed past the Studio loopback guard (comma-separated). Leave empty\n"
        "# for localhost-only use; NEVER disable the guard.\n"
        "HIMMY_STUDIO_ALLOW_HOSTS=\n"
    )


def _write_file(path: Path, content: str, *, mode: int | None) -> None:
    """Write ``content`` to ``path`` (creating parents), optionally chmod-ing it.

    Existence is checked up-front by the caller across the WHOLE target set, so this
    helper unconditionally writes — it must only be reached once the caller has
    decided every file is safe to write (avoiding a partial .env/secret divergence).
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if mode is not None:
        path.chmod(mode)


def cmd_provision(args: argparse.Namespace) -> int:
    base = Path(args.dir)
    secrets_dir = base / _SECRETS_SUBDIR
    env_path = base / _ENV_NAME
    pg_path = secrets_dir / _PG_PASSWORD_FILE

    pg_password = _gen_password()
    api_key = _gen_api_key()

    # Build the FULL set of files this run would write (secret(s) first, then .env
    # referencing the same password) before touching the disk.
    planned: list[tuple[Path, str]] = [(pg_path, pg_password + "\n")]
    if args.encryption_key:
        planned.append((secrets_dir / _ENCRYPTION_KEY_FILE, _gen_encryption_key()))
    planned.append((env_path, _render_env(pg_password, api_key)))

    # Atomic-ish guard: if ANY target already exists and we're not forcing, refuse
    # BEFORE writing any of them. Writing the secret then erroring on .env (or vice
    # versa) would rotate one value and leave the pair divergent — the exact failure
    # this script exists to prevent.
    if not args.force:
        existing = [p for p, _ in planned if p.exists()]
        if existing:
            joined = ", ".join(str(p) for p in existing)
            raise SystemExit(
                f"error: {joined} already exist(s) — pass --force to overwrite "
                "(this rotates the value(s); existing data may become unreadable)"
            )

    for path, content in planned:
        _write_file(path, content, mode=0o600)
        _eprint(f"wrote {path}")

    print(f"provisioned {base} (.env + secrets/{_PG_PASSWORD_FILE})")

    compose_path = base / _COMPOSE_FILE
    if args.up:
        if not compose_path.is_file():
            _eprint(f"warning: {compose_path} not found — skipping `compose up`")
        else:
            _eprint(f"bringing up {compose_path} …")
            subprocess.run(  # noqa: S603 - fixed argv, no shell
                ["docker", "compose", "-f", str(compose_path), "up", "-d"],  # noqa: S607
                check=True,
            )
            return 0
    if compose_path.is_file():
        print(f"next: docker compose -f {compose_path} up -d")
    else:
        print(
            "next: place a docker-compose.yml in this dir, then `docker compose up -d`"
        )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--dir",
        default=_DEFAULT_DIR,
        help="compose dir to provision (default deploy/compose)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing .env / secret files (rotates their values)",
    )
    parser.add_argument(
        "--encryption-key",
        action="store_true",
        help="also generate a base64 KEK secret for encryption-at-rest",
    )
    parser.add_argument(
        "--up",
        action="store_true",
        help="run `docker compose up -d` after provisioning (if the file exists)",
    )
    parser.set_defaults(func=cmd_provision)
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
